# My web site settings

# site basic info
site_name: Min Xu's web site
site_url: https://minxu74.github.io
site_author: Min Xu
site_description: >-
   Host my bio, projects, and blogs 

# repository
repo_name: minxu74/minxu74.github.io
repo_url: https://github.com/minxu74/minxu74.github.io

# Copyright
copyright: Copyright &copy; 2024 Min Xu

# mkdocs conf
theme:
   name: material
   custom_dir: overrides
   features:
      - announce.dismiss
      - toc.follow
      #- toc.integrate  # not compatible with indexes
      - navigation.footer
      #- navigation.tabs
      - navigation.top
      #- navigation.path #inside
      - navigation.instant
      #- navigation.sections
      - navigation.expand
      - navigation.prune
      - navigation.indexes
      - search.highlight
      - search.share
      - search.suggest
      - content.tooltip
      - content.code.copy    # button to copy code
      - content.code.annotate  # allow code annotation
      - content.action.view
      #- content.action.edit
   font:
      text: Open Sans 300 #Oswald #Open Sans  #Raleway
      code: Roboto Mono
   #favicon: assets/image/favicon.png
   favicon: assets/image/favicon.png
   icon:
      repo: fontawesome/brands/github-alt
      logo: fontawesome/solid/globe
      annotation: material/alpha-b-circle
   #logo: assets/image/logo.png

   # Palette toggle for light mode
   palette: 
      - scheme: default
        toggle:
          icon: material/desk-lamp-off
          name: Switch to dark mode
 
      # Palette toggle for dark mode
      - scheme: slate
        toggle:
          icon: material/desk-lamp-on
          name: Switch to light mode


# extra conf
extra:
   social:
      - icon: fontawesome/brands/github
        link: https://github.com/minxu74 
      - icon: fontawesome/brands/linkedin
        link: https://linkedin.com/in/minxu74
   analytics:
        provider: google
        property: G-S2E4FP4ER0



# extensions
markdown_extensions:
   - meta
   - admonition # callouts/annotations
   - pymdownx.emoji:
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
        emoji_index: !!python/name:material.extensions.emoji.twemoji
   - toc:
        permalink: true
   - md_in_html
   - attr_list
   - def_list
   - pymdownx.details # add collapsible call-outs
   - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
   - pymdownx.tabbed:
        alternate_style: true   # enable content tab
   - pymdownx.caret # define superscript
   - pymdownx.mark # highlight text
   - pymdownx.tilde # define subscript
   - pymdownx.critic # track changes
   - footnotes
   - customblocks  # create a block
   - pymdownx.highlight: # highlight of code blocks
        linenums_style: pymdownx-inline
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
   - pymdownx.inlinehilite # highlight inline code blocks
   - pymdownx.arithmatex:
        generic: true


# plugins
plugins:
  - search
  - git-revision-date-localized:
       enable_creation_date: true
       fallback_to_build_date: true
       type: iso_date
       timezone: America/New_York
       locale: en 
       exclude:
           - index.md
           - blog/*
           - jupyternb/*.ipynb
       enabled: true
       strict: false
  - git-committers:
       repository: minxu74/minxu74.github.io
       branch: master
  - bibtex:
       bib_file: "docs/assets/bib/MXPUB.bib"
       csl_file: "docs/assets/csl/american-geophysical-union.csl"
       cite_inline: False
  - link-embeds:
      enabled: true
      name_default: "Untitled Link"
      desc_default: "No description found"
      image_default: "https://github.com/Aetherinox/mkdocs-link-embeds/assets/118329232/c0298d98-0910-4235-a88f-0c3e2f704ba7"
      image_disabled: false
      favicon_default: "https://github.com/Aetherinox/mkdocs-link-embeds/assets/118329232/b37da9c6-6f17-4c3f-9c94-c346a6f31bfa"
      favicon_disabled: false
      favicon_size: 25
      target: "blank"
      accent: "FFFFFF1A"
      verbose: false
  - blog:
      blog_dir: blog
      post_dir: "{blog}/posts"
      post_date_format: full
      post_url_date_format: yyyy/MM
      post_url_format: "{date}/{slug}"
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
         kwds:
           case: lower
      post_excerpt: optional
      post_excerpt_separator: <!-- more -->
      post_readtime: false
      post_readtime_words_per_minute: 260
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
         kwds:
           case: lower
      categories_allowed:
         - General
         - Science
         - Computer
      authors: true
      authors_file: "{blog}/.authors.yml"
      pagination: true
      pagination_per_page: 5
  - mkdocs-jupyter
  #- include-markdown  # tried and it is so slow
  #- mknotebooks
  #- redirects:
  #    redirect_maps:
  #       'projects/gpu.md': 'https://gpu.org'

  - glightbox:  # tried very slow, add 10 times time in building
                # find the problem caused by the conflict with link-embed
                # disable glightbox in frontmatter in the page with link-embed
      touchNavigation: true
      loop: false
      effect: none
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: true

# main page tree
nav:
   - About me: 
       - index.md
   - Projects: 
       - projects/index.md
       - RUBISCO: projects/rubisco.md
       - ESGF2: projects/esgf2.md
       - Geoengineering: projects/geoengineering.md
       - GPU optimization: projects/gpu.md
   - Publications: 
       - publications/index.md
       - Presentations: publications/present.md
       - Posters: publications/poster.md
   - Tools: 
       - tools/index.md
   - Jupyter Notebook Showcase: 
       - jupyternb/index.md
       - Plot NBP time series: jupyternb/check_nbp.ipynb
   - Test page:
       - test/index.md
   - Blog:
       - blog/index.md




# extra
extra_css:
   - assets/stylesheets/link-embeds.css

extra_javascript:
   - assets/javascripts/change-annotation-icon.js
   - assets/javascripts/mathjax.js
   - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
