# My web site settings

# site basic info
site_name: Min Xu's web site
site_url: https://minxu74.github.io
site_author: Min Xu
site_description: >-
   Host my bio, projects, and blogs 

# repository
repo_name: minxu74/minxu74.github.io
repo_url: https://github.com/minxu74/minxu74.github.io

# Copyright
copyright: Copyright &copy; 2024 Min Xu

# mkdocs conf
theme:
   name: material
   features:
      - announce.dismiss
      - toc.follow
      #- toc.integrate  # not compatible with indexes
      - navigation.footer
      - navigation.sections
      #- navigation.tabs
      - navigation.top
      - navigation.path
      - navigation.instant
      - navigation.sections
      - navigation.expand
      - navigation.prune
      - navigation.indexes
      - search.highlight
      - search.share
      - search.suggest
      - content.tooltip
      #- content.action.view
      #- content.action.edit
   font:
      text: Open Sans #Oswald #Open Sans  #Raleway
      code: Roboto Mono
   #favicon: assets/image/favicon.png
   favicon: assets/image/favicon.png
   icon:
      repo: fontawesome/brands/github-alt
      logo: fontawesome/solid/globe
      annotation: material/alpha-b-circle
   #logo: assets/image/logo.png

   # Palette toggle for light mode
   palette: 
      - scheme: default
        toggle:
          icon: material/desk-lamp-off
          name: Switch to dark mode
 
      # Palette toggle for dark mode
      - scheme: slate
        toggle:
          icon: material/desk-lamp-on
          name: Switch to light mode


# extra conf
extra:
   social:
      - icon: fontawesome/brands/github
        link: https://github.com/minxu74 
      - icon: fontawesome/brands/linkedin
        link: https://linkedin.com/in/minxu74

# extensions
markdown_extensions:
   - admonition
   - pymdownx.emoji:
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
        emoji_index: !!python/name:material.extensions.emoji.twemoji
   - toc:
        permalink: true
   - md_in_html
   - attr_list
   - pymdownx.details
   - pymdownx.superfences
   - footnotes

# plugins
plugins:
  - search
  - bibtex:
       bib_file: "docs/assets/bib/MXPUB.bib"
       csl_file: "docs/assets/csl/american-geophysical-union.csl"
       cite_inline: False


# main page tree
nav:
   - About me: 
       - index.md
   - Projects: 
       - projects/index.md
   - Publications: 
       - publications/index.md
   - Blog:
       - blog/index.md
